package me.authorname.examplemod.mixins;

import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.objectweb.asm.tree.ClassNode;
import org.spongepowered.asm.launch.MixinLaunchPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinConfigPlugin;
import org.spongepowered.asm.mixin.extensibility.IMixinInfo;

import java.util.List;
import java.util.Set;

import static me.authorname.examplemod.ExampleMod.LOGGER;

public class MixinPlugin implements IMixinConfigPlugin {
    private static final Marker IT = MarkerManager.getMarker(MixinPlugin.class.getSimpleName());

    @Override
    public void onLoad(String mixinPackage) {
        // IS CALLED WHEN A MIXIN IS LOADED
        LOGGER.info(IT,"Loading mixin: {}", mixinPackage);
    }

    @Override
    public String getRefMapperConfig() {
        // You should ignore this
        // refmap is generated by MixinGradle
        return null;
    }

    @Override
    public boolean shouldApplyMixin(String targetClassName, String mixinClassName) {
        // Check if any mixin should be applied, false for prevent application
        return false;
    }

    @Override
    public void acceptTargets(Set<String> myTargets, Set<String> otherTargets) {
        // TODO: Missing doc
    }

    @Override
    public List<String> getMixins() {
        // YOU SHOULD IGNORE THIS
        return null;
    }

    @Override
    public void preApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        // ALWAYS KEEP THIS, IS HELPFULLY FOR OTHER DEVELOPERS IN CASE YOUR MOD MODIFIES A LOT MINECRAFT BEHAVIOR
        LOGGER.debug(IT, "Applying mixin '{}' to target class {}", mixinClassName, targetClassName);
    }

    @Override
    public void postApply(String targetClassName, ClassNode targetClass, String mixinClassName, IMixinInfo mixinInfo) {
        LOGGER.debug(IT, "Mixin '{}' applied successfully", mixinClassName);
    }
}
