modLoader="javafml"
loaderVersion="${fmlrange}"
license="${modlicense}"
[[mods]]
modId="${modid}"
version="${version}"
displayName="${modname}"
authors="${modauthors}"
description='''${mod_description}'''

# DEPENDENCIES
[[dependencies.${modid}]]
   modId="forge"
   mandatory=true
   versionRange="${fgrange}"
   ordering="NONE"
   side="CLIENT"

[[dependencies.${modid}]]
   modId="minecraft"
   mandatory=true
   versionRange="${mcrange}"
   ordering="NONE"
   side="CLIENT"

[[dependencies.${modid}]]
   modId="embeddium"
   mandatory=true
   versionRange="${embeddiumrange}"
   ordering="AFTER"
   side="CLIENT"